version: '3.0'
services:
  db:
    image: postgres
    volumes:
      - ./container-data/postgres:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    privileged: false
    restart: always
    # to persist rabbitmq container data it needs to set hostname and volume
    hostname: rabbitmq
    volumes:
      - "./container-data/rabbitmq:/var/lib/rabbitmq/mnesia/"
    ports:
      - "5672:5672"
  consumer:
    build: src/consumer_django_project/.
    command: sh run_worker.sh
    volumes:
      - ./src/consumer_django_project:/code
      - ./container-data/celery/:/var/run/celery/
    environment:
      CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq"
      POSTGRES_NAME: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
    depends_on:
      - db
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 3 # number of consumer workers
  producer:
    build: src/producer_django_project/.
    command: sh run_server.sh
    volumes:
      - ./src/producer_django_project:/code
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq"
      POSTGRES_NAME: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
    depends_on:
      - db
    env_file:
      - .env