#!/bin/bash
set -ex

psql -v ON_ERROR_STOP=1 -v PROJECT_POSTGRES_USER="$PROJECT_POSTGRES_USER" -v POSTGRES_NAME="$POSTGRES_NAME" --username "$POSTGRES_USER" --dbname "$POSTGRES_DB"<<-EOSQL
    CREATE USER :"PROJECT_POSTGRES_USER";
    CREATE DATABASE :"POSTGRES_NAME";
    GRANT ALL PRIVILEGES ON DATABASE :"POSTGRES_NAME" TO :"PROJECT_POSTGRES_USER";
EOSQL